numeric_fmt  <- "##.##"
n_obs <- "##"
count_fmt <- "## (##.##%)"
blanks <- ""
pval <- "#.###"
ci95 <- "##.##: ##.##"
mean.sd <- "##.## (##.##)"
subjid <- "########"
date.time <- "YYYY-MM-DD"
string_fmt <- "xx"
